name: synbiodio_core
description: The Core of Synbiodio. This package is the core package under synbiodio, which encapsulates the underlying common functions.
version: 0.3.4
homepage: https://github.com/synbiodio-com/synbiodio_core

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  logger: ^2.0.0
  path: ^1.8.3
  path_provider: ^2.1.0
  uuid: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1
