name: synbiodio_core
description: The Core of Synbiodio. This package is the core package under synbiodio, which encapsulates the underlying common functions.
version: 0.1.0
homepage: https://github.com/synbiodio-com/synbiodio_core

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0
  uuid: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
