name: synbiodio_core
description: The Core of Synbiodio.
version: 0.0.3
homepage: https://github.com/synbiodio-com/sysbiodio_core

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0
  uuid: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
