name: synbiodio_core
description: The Core of Synbiodio.
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ">=3.1.0 <5.0.0"
